- Defs/ThingDefs/Weapons_CE_Guns.xml
Added bipod tags to respected weapons using them. Intended to have the PR ready when the main Bipods PR gets merged.
> Bipod tag insertion

- Defs/ThingDefs/Weapons_CE_Guns.xml
What it says on the tin
It enables Men in black to spawn with Taurus Judges
> Added Revolver tag to the Taurus Judge

- Defs/ThingDefs/Weapons_CE_Guns.xml
Set the Taurus Judge's ammoset to the proper one using the new slow .410 projectile instead of the normal one
Fixed some one-handed weapon tags
> Taurus Judge rebalanced

- Defs/ThingDefs/Weapons_CE_Guns.xml
Increased the Spread on the flamethrower to give it a more flamethrower feel
> Flamethrower Spread

- Patches/Combat Extended/Weapons_Guns.xml
- Added a patch that renames the LAW recipe to its real name.
> Fixed LAW recipe label

- Defs/ThingDefs/Weapons_CE_Guns.xml
Changed the charge sniper rifle from using 8x35mm Charged to 8x50mm Charged
> Charge Sniper rechambering

- Defs/ThingDefs/Weapons_CE_Guns.xml
Fixed some capitalizing stuff and missing tech levels
Commented out the unused base parent defs
> Misc. Tweaks

- Defs/ThingDefs/Weapons_CE_Guns.xml
> Crossbow range consistency check

- Defs/ThingDefs/Weapons_CE_Guns.xml
- Added appropriate weapon classes to the added weapons by the mod and tweaked the weapon tags appropriately.
- Added thingSetMakerTags which in turn mean quest reward tags to the melee weapons added by the mod.
> Weapon tags tweaks and weapons classes addition

- Defs/ThingDefs/Weapons_CE_Guns.xml
Fixed the material requirements in the Hecate's crafting recipe which somehow was messed up.
New values are based on this spreadsheet results:
https://docs.google.com/spreadsheets/d/1WbHYBy12WmoQ50jIzoJga_B0qhv4wlZnkEAnGiPuto4/edit#gid=884124215
> Hecate recipe fix

- Defs/ThingDefs/Weapons_CE_Guns.xml
> AKS warmup from 0.85 to 0.9

- Defs/ThingDefs/Weapons_CE_Guns.xml
While I understand that it's a proper name, it makes looking it up with any text search functions like that of storage or Dubs Mint Menus trickier.
> Rename Hécate to Hecate

- Defs/ThingDefs/Howitzer.xml
Similar to https://github.com/CombatExtended-Continued/CombatExtended/pull/1668
> Howitzer terrain affordance fix

- Defs/ThingDefs/Howitzer.xml
What it says on the tin, similar to https://github.com/CombatExtended-Continued/CombatExtended/pull/1733
> Adjust Howitzer gun's mass

- Defs/ThingDefs/Weapons_CE_Guns.xml
Similar to https://github.com/CombatExtended-Continued/CombatExtended/pull/1760
> Fire mode tweaks

- Patches/Combat Extended/Weapons_Guns.xml
> Patch the x1 LAW crafting recipe's label

- Defs/ThingDefs/Weapons_CE_Guns.xml
What it says on the tin, certain values were not accurate to the gun spreadsheet.
https://docs.google.com/spreadsheets/d/1lbT0zzagCRPDJG4GctkeeoTsFCt3lYfM4SRnWt8ql-k/edit#gid=1573763037
> Fixed some values based on the spreadsheet

- Defs/ThingDefs/Weapons_CE_Guns.xml
Switch the two AMRs from having the DMR bipods tag to AMR ones.
> Implement AMR bipods tags

- Defs/ThingDefs/Weapons_CE_Guns.xml
Similar to: https://github.com/CombatExtended-Continued/CombatExtended/pull/1880
> NoRack shot sound for the USAS

- Defs/ThingDefs/Weapons_CE_Guns.xml
Similar to https://github.com/CombatExtended-Continued/CombatExtended/pull/1888
> Recoil value adjustments

- Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
What it says on the tin, a change in parallel to https://github.com/CombatExtended-Continued/CombatExtended/pull/1905
> Rename the vanilla LMG  to the Bren Mk4

- 1.4/Defs/ThingDefs/Weapons_CE_Guns.xml
Fix the ParentName issues that was causing weapons from CE Guns to not appear in trader stocks.
> ParentName issues fix

- 1.4/Defs/ThingDefs/Weapons_CE_Guns.xml
- README.md
Forgot to update the names in the readme file...
Updated the Winchester 94's weapon tag in accordance to https://github.com/CombatExtended-Continued/CombatExtended/pull/2152
> Update the charge guns' names in the readme file

- 1.4/Defs/ThingDefs/Howitzer.xml
What it says on the tin, in accordance with https://github.com/CombatExtended-Continued/CombatExtended/pull/2209
> Howitzer flammability adjustment

- 1.4/Defs/ThingDefs/Weapons_CE_Guns.xml
Aligned some misaligned texture offsets and centered the barrels.
> Fix weapon draw offsets

- 1.4/Defs/ThingDefs/Weapons_CE_Guns.xml
Add the AmmoGenPerMagOverride node to the appropriate weapons.
> Add the AmmoGenPerMagOverride node and other tweaks
